[CmdletBinding()]
param()

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$repositoryRoot = [System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..'))
$failures = New-Object System.Collections.Generic.List[string]

Write-Host 'Parsing PowerShell files...' -ForegroundColor Cyan
Get-ChildItem -LiteralPath $repositoryRoot -Filter '*.ps1' -Recurse | ForEach-Object {
    $tokens = $null
    $parseErrors = $null
    [System.Management.Automation.Language.Parser]::ParseFile($_.FullName, [ref]$tokens, [ref]$parseErrors) | Out-Null
    foreach ($parseError in $parseErrors) {
        $failures.Add("$($_.FullName):$($parseError.Extent.StartLineNumber): $($parseError.Message)")
    }
}

Write-Host 'Running toolkit contracts...' -ForegroundColor Cyan
& powershell.exe -NoProfile -ExecutionPolicy Bypass -File (Join-Path $repositoryRoot 'tests\Toolkit.Tests.ps1')
if ($LASTEXITCODE -ne 0) { $failures.Add('Toolkit.Tests.ps1 failed.') }

Write-Host 'Checking tracked artifacts...' -ForegroundColor Cyan
$trackedFiles = & git -C $repositoryRoot ls-files
if ($LASTEXITCODE -ne 0) { $failures.Add('git ls-files failed.') }
$forbiddenExtensions = @('.apk', '.aab', '.apks', '.class', '.dex', '.jks', '.keystore', '.zip')
foreach ($trackedFile in $trackedFiles) {
    if ($forbiddenExtensions -contains [System.IO.Path]::GetExtension($trackedFile).ToLowerInvariant()) {
        $failures.Add("Generated or downloaded binary is tracked: $trackedFile")
    }
}

$forbiddenTokens = @(
    ('co' + 'dex'),
    ('open' + 'ai'),
    ('chat' + 'gpt'),
    ('co-' + 'authored-by'),
    ('generated by ' + 'ai')
)
$forbiddenPattern = $forbiddenTokens -join '|'
$attributionMatches = & git -C $repositoryRoot grep -I -n -E $forbiddenPattern 2>$null
if ($LASTEXITCODE -eq 0) {
    foreach ($match in $attributionMatches) { $failures.Add("Forbidden attribution text: $match") }
} elseif ($LASTEXITCODE -gt 1) {
    $failures.Add('git grep failed while checking attribution text.')
}

$commitMessages = (& git -C $repositoryRoot log --format=%B) -join "`n"
foreach ($token in $forbiddenTokens) {
    if ($commitMessages.IndexOf($token, [System.StringComparison]::OrdinalIgnoreCase) -ge 0) {
        $failures.Add("Forbidden attribution text found in commit messages: $token")
    }
}

$suBridge = Join-Path $repositoryRoot 'assets\magisk-module\system\system_ext\bin\su'
if (Test-Path -LiteralPath $suBridge -PathType Leaf) {
    $bytes = [System.IO.File]::ReadAllBytes($suBridge)
    if ($bytes -contains 13) { $failures.Add('The Android su bridge contains CRLF line endings.') }
}

if ($failures.Count -gt 0) {
    foreach ($failure in $failures) { Write-Host "FAIL: $failure" -ForegroundColor Red }
    throw "$($failures.Count) toolkit verification failure(s)."
}

Write-Host 'Toolkit verification passed.' -ForegroundColor Green
